import "bootstrap/dist/css/bootstrap.min.css"
import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"

import "./src/styles/main.css"
import "./src/styles/styles.css"
import "./src/styles/firewatchlaunch.css"
import "./src/styles/firewatchlaunchadd3.css"
import "./src/styles/slick.css"
import "./src/styles/slick.module.css"
import "./src/assets/css/fontawesome.css"
import "./src/assets/css/style.css"
import "./src/assets/css/responsive.css"
